### ISSUE TITLE
Create an example where operator spec struct can be used in go-client

### ISSUE THREAD

**Issue by goswamig** [aws/amazon-sagemaker-operator-for-k8s#119]
Customer request: https://github.com/aws/amazon-sagemaker-operator-for-k8s/issues/118

**Comment by song-william** [comment]
Excited to see this!

**Comment by surajkota** [comment]
Please use the [latest version of SageMaker Operator](https://github.com/aws-controllers-k8s/sagemaker-controller) - https://github.com/aws/amazon-sagemaker-operator-for-k8s#migrate-resources-to-the-new-sagemaker-operators-for-kubernetes
