### ISSUE TITLE
Upgrade aws-sdk to v1

### ISSUE THREAD

**Issue by EngHabu** [aws/amazon-sagemaker-operator-for-k8s#165]
**What would you like to be added**:
Upgrade dependency to the stable aws-sdk v1.. it's a breaking change so a lot will need to be updated.

**Why is this needed**:
Unable to consume any of new SDK types because we have a dependency on the operator.

**Comment by mbaijal** [comment]
Hello Haytham, 
Thank you for your request. We do not have a decision on this currently and we'll get back to you. 

Meghna Baijal

**Comment by surajkota** [comment]
Please update to v1.2.0 which has the changes requested.
