### ISSUE TITLE
Improve HAP logging message

### ISSUE THREAD

**Issue by mbaijal** [aws/amazon-sagemaker-operator-for-k8s#189]
**What would you like to be added**:
As discussed in [this issue](https://github.com/aws/amazon-sagemaker-operator-for-k8s/issues/185) there are two action items here - 
1. Improve the existing HAP controller log message to be more specific.
2. Verify the server side errors are surfacing correctly for HAP (I did not see the right error message when specifying the incorrect endpoint `region`. Need to verify if this is due to incorrect operator implementation or GoSDK)

**Why is this needed**:
Improve debugging and thus better user experience.

**Comment by surajkota** [comment]
Please use the [latest version of SageMaker Operator](https://github.com/aws-controllers-k8s/sagemaker-controller) - https://github.com/aws/amazon-sagemaker-operator-for-k8s#migrate-resources-to-the-new-sagemaker-operators-for-kubernetes
