### ISSUE TITLE
Add checksum file to enable the installation of the chart from helm

### ISSUE THREAD

**Issue by MarcelNasser** [aws/amazon-sagemaker-operator-for-k8s#190]
**What would you like to be added**:
Add a file with checksums (index.yaml) to enable helm or terraform to install the chart automatically from this github repo.
 
**Why is this needed**:
For chart installation automation.

**Comment by surajkota** [comment]
Please use the latest version of SageMaker Operator - https://github.com/aws/amazon-sagemaker-operator-for-k8s#migrate-resources-to-the-new-sagemaker-operators-for-kubernetes
