### ISSUE TITLE
StepScaling policy support

### ISSUE THREAD

**Issue by patrick-239** [aws/amazon-sagemaker-operator-for-k8s#195]
**What would you like to be added**:
It would be great is this tool will allow to use StepScaling policy additionally to TargetTrackingScaling policy. 

**Why is this needed**:
Some companies currently using StepScaling policy as a infrastructure standard and they could not use amazon-sagemaker-operator-for-k8s as it doesn't support this policy.

**Comment by surajkota** [comment]
Please see feature request in https://github.com/aws-controllers-k8s/community/issues/1706

This repository will be archived - https://github.com/aws/amazon-sagemaker-operator-for-k8s#migrate-resources-to-the-new-sagemaker-operators-for-kubernetes
