### ISSUE TITLE
Async Endpoint Request

### ISSUE THREAD

**Issue by dferguson992** [aws/amazon-sagemaker-operator-for-k8s#198]
Hello!

Will there be any support for Async Inference Endpoints?

**Comment by surajkota** [comment]
Hi @dferguson992, thanks for the feature request. Support for [Asynchronous Inference Endpoint](https://docs.aws.amazon.com/sagemaker/latest/dg/async-inference-create-endpoint.html) is available in the latest [SageMaker operator based on the ACK framework](https://github.com/aws-controllers-k8s/sagemaker-controller). Here are the parameters you need to specify in EndpointConfig CR: https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/config/crd/bases/sagemaker.services.k8s.aws_endpointconfigs.yaml#L39-L71

If you are new to ACK service controller for SageMaker, here is a tutorial to get you started: https://aws-controllers-k8s.github.io/community/docs/tutorials/sagemaker-example/
