### ISSUE TITLE
Migrating to v1 as v1beta is deprecated

### ISSUE THREAD

**Issue by asosnovsky-sumologic** [aws/amazon-sagemaker-operator-for-k8s#205]
Starting with k8s 1.22 the v1beta `CustomResourceDefinition` will be deprecated see https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes

Which means that the code in this repo will no longer be applicable. Is there any plans to migrate the definitions?

**Comment by surajkota** [comment]
Hi @asosnovsky-sumologic, thanks for the question, are you able migrate to using the new SageMaker operator based on AWS controllers for Kubernetes framework? - https://github.com/aws-controllers-k8s/sagemaker-controller

It offers similar functionality and supports more SageMaker features. We have a migration guide as well - https://docs.aws.amazon.com/sagemaker/latest/dg/kubernetes-sagemaker-operators-migrate.html

**Comment by surajkota** [comment]
Hi, We are stopping the development and technical support of [SageMaker Operators for Kubernetes](https://github.com/aws/amazon-sagemaker-operator-for-k8s/tree/master) in its original version. If you are currently using version v1.2.2 or below of the original version of SageMaker Operators for Kubernetes, we recommend migrating your resources to thelatest SageMaker Operators for Kubernetes, the [ACK service controller for Amazon SageMaker](https://github.com/aws-controllers-k8s/sagemaker-controller) based on [AWS Controllers for Kubernetes (ACK)](https://aws-controllers-k8s.github.io/community/).
For information about the migration steps, see [Migrate resources to the latest Operators](https://docs.aws.amazon.com/sagemaker/latest/dg/kubernetes-sagemaker-operators-migrate.html).
For answers to frequently asked questions regarding the end of support of the original version of SageMaker Operators for Kubernetes, see [Announcing the End of Support of the Original Version of SageMaker Operator for Kubernetes](https://docs.aws.amazon.com/sagemaker/latest/dg/kubernetes-sagemaker-operators-eos-announcement.html)
