### ISSUE TITLE
Unify the model name between batch transform and hosting deployments.

### ISSUE THREAD

**Issue by goswamig** [aws/amazon-sagemaker-operator-for-k8s#59]
Currently model name in [hosting deployment](https://github.com/aws/amazon-sagemaker-operator-for-k8s/blob/master/tests/codebuild/testfiles/xgboost-hosting-deployment.yaml#L14) uses kubernetes name of model while model in [batch transform](https://github.com/aws/amazon-sagemaker-operator-for-k8s/blob/master/tests/codebuild/testfiles/xgboost-mnist-batchtransform.yaml#L7) uses sagemaker model name. 

Ideally we should have same mechanism for name, given that kubernetes user will look from kubernetes lens.

**Comment by surajkota** [comment]
closing in favor of existing issue in SIM
