### ISSUE TITLE
Short name for jobs

### ISSUE THREAD

**Issue by goswamig** [aws/amazon-sagemaker-operator-for-k8s#69]
K8s often has short name for their resources. We should model the job name as short job name. 

One suggestion 
```
hyperparametertuningjobs      ===>  hptj or hpo
trainingjobs   ===> tj
batchtransformjobs  ===>  btj
endpointconfigs  ===>  epc or ec
hostingdeployments ===> hd 
models  ==> m
```
We should make sure we don't conflict with any existing k8s resources short name

**Comment by surajkota** [comment]
Closing in favor of existing issue in SIM. (Search by the github issue number)
